### ISSUE TITLE
how to invert the selectedCallback?

### ISSUE THREAD

**Issue by gladson** [imaNNeoFighT/circular_bottom_navigation#13]
I want to invert the selection of the circular bottom navigation, by clicking on enabled it activates the other.

**Comment by imaNNeo** [comment]
I didn't get you

**Comment by gladson** [comment]
> I didn't get you

Thanks for listening.
I would like a way to reverse the selections.

For example in the tabitems listing the one that was enabled would appear as disabled.

**Comment by imaNNeo** [comment]
Sorry didn't get you again :)

**Comment by gladson** [comment]
Reverse selected to unselected

![](https://i.imgur.com/AbkWH53.png)

**Comment by imaNNeo** [comment]
Ok got it,
We are not gonna handle this state because as you know in the bottom sheet there should be one selected item (as we should show a page in the app.
so if you wanna achieve this, you can fork the project and change it as you want.

**Comment by gladson** [comment]
> Ok got it,
> We are not gonna handle this state because as you know in the bottom sheet there should be one selected item (as we should show a page in the app.
> so if you wanna achieve this, you can fork the project and change it as you want.

Ok, thank you very much for the feedback.
