### ISSUE TITLE
Shadow is not configurable

### ISSUE THREAD

**Issue by SaadArdati** [imaNNeoFighT/circular_bottom_navigation#17]
Heya! The shadow applied to the background bar is not configurable.
It's very obvious in this screenshot: 
![image](https://user-images.githubusercontent.com/7407478/68249653-e392e180-0027-11ea-9ca5-d5212e76f05c.png)

I'd love an option to turn it off. It would enable material design foundations even,

**Comment by benyaminbeyzaie** [comment]
Checkout the PR and set `backgroundBoxShadow: <BoxShadow>[]` on your `CircularBottomNavigation` to remove shadows
