### ISSUE TITLE
Would nice to have :)

### ISSUE THREAD

**Issue by blntylmn** [imaNNeoFighT/circular_bottom_navigation#2]
Thanks for this plugin. I am newbie at Flutter also dart (coming from react native side) bu really love it.
So I can't help  at least now :( but it would be nice to see these options :
`barBackgroundColor`
`circleStrokeColor`
`barTopBorderColor`
`barTopBorderWidth`
`animationDuration`

**Comment by imaNNeo** [comment]
Hi, Thank you for contribute (absolutely this is contribute),
I agree with ```barBackgroundColor``` and ```animationDuration```
But about ```circleStrokeColor``` It's better to set this color as same as ```barBackgroundColor```
because the design will broke by separating these two,
and about ```barTopBorderColor``` and ```barTopBorderWidth```, currently we haven't barTopBorder, firstly we should add it to library.

**Comment by imaNNeo** [comment]
```barBackgroundColor``` and ```animationDuration``` added, they are exists on 0.9.1 version
