### ISSUE TITLE
Conflict with _Controllers

### ISSUE THREAD

**Issue by Dr-Legend** [imaNNeoFighT/circular_bottom_navigation#21]
I am  Using  https://pub.dev/packages/solid_bottom_sheet#-readme-tab-
this package and when I tried to open the bottom sheet in onSelected callback of CircularBottomNavigation
it changes the value of the bottom sheet controller too

**Comment by benyaminbeyzaie** [comment]
Closing this cause it is not active for years! If the issue persists please open another one and describe the problem. Thanks!
