### ISSUE TITLE
Allow callback even when icon doesn't change

### ISSUE THREAD

**Issue by samurajj** [imaNNeoFighT/circular_bottom_navigation#25]
Info: My app has more than 5 pages. If I navigate deeper, it all works, I can even select which icon from menu corresponds to the subpage, all good.
Problem: I can't go back to the initial page simply by tapping the icon from this menu. When I want to do it from menu, I have to select some other icon first and only after that the one I want.
Suggestion: Would it be possible to add bool parametr to allow this callback? 
Other suggestion: Would it be possible to have no icon selected?

Or am I overlooking something?
Thanks

**Comment by hugobrancowb** [comment]
hey! I am pretty much done with this implementation if it's still in this project's interests. I was wondering, tho, which hitbox could suit better user's experience. hitboxed are illustrated by the green border below

<div align=center><img src="https://user-images.githubusercontent.com/11953552/195868089-4bf8e540-f7d8-487a-a62f-2ceda6135008.png" width=500/></div>
