### ISSUE TITLE
The library 'package:circular_bottom_navigation/tab_item.dart' is legacy

### ISSUE THREAD

**Issue by cphilc** [imaNNeoFighT/circular_bottom_navigation#29]
→  and should not be imported into a null safe library. Try migrating the imported library.

Here is the report from **dart pub outdated --mode=null-safety** 

Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name                Current  Upgradable  Resolvable  Latest  

direct dependencies:       
circular_bottom_navigation  ✗1.0.1   ✗1.0.1      ✗1.0.1      ✗1.0.1  

**My config:**
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (3 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**Comment by benyaminbeyzaie** [comment]
Use the last version please the null safety issue is fixed and published
