### ISSUE TITLE
FontAwesome Icons issue

### ISSUE THREAD

**Issue by ahmedkassem** [imaNNeoFighT/circular_bottom_navigation#3]
Thanks for the great package , I got a small problem when using FontAwesome icons are not centered within the circle, i tried changing the iconSize , but still not centered

![Screenshot_2019-04-12-18-17-08-120_com example schoolapp](https://user-images.githubusercontent.com/7607004/56051618-8fed3d80-5d4f-11e9-95ad-1b0f7cb137d5.png)

**Comment by imaNNeo** [comment]
Hi,
Okay let's fix it,
may I ask you share your code?
and which font awesome you are used?

**Comment by ahmedkassem** [comment]
font_awesome_flutter: ^8.4.0
I used the code in the example folder:
  List<TabItem> tabItems = List.of([
    new TabItem(FontAwesomeIcons.newspaper, "News", Colors.orange),
    new TabItem(FontAwesomeIcons.calendarAlt, "Calendar", Colors.red),
    new TabItem(FontAwesomeIcons.home, "Home", Colors.blue),
    new TabItem(FontAwesomeIcons.bars, "Other", Colors.cyan),
  ]);

**Comment by imaNNeo** [comment]
Okay dude,
I am busy a little, But I will check it ASAP.

**Comment by ahmedkassem** [comment]
ok thanks a lot

**Comment by imaNNeo** [comment]
Hi,
I checked it but I think it's font awesome issue, not this library,
Check these images:
<img src="http://uupload.ir/files/mqgk_photo_2019-04-17_00-20-03.jpg" width="600">
<img src="http://uupload.ir/files/eiqi_photo_2019-04-17_00-19-55.jpg" width="600">

I set a background color for drawed images,
The first one is the Material Icons,
The second one is the FontAwesome icons, the fonts drawn outside the background with the bottomRight gravity,
I think you should open an issue on the FontAwesome library.
