### ISSUE TITLE
Enhancement: Bottom bar with scrollable 

### ISSUE THREAD

**Issue by ArivuLabs** [imaNNeoFighT/circular_bottom_navigation#4]
Hi
Excellent bottom bar menu;  :)

I was wondering if you can add a scrollable for TabItem on the bottom.

I am referring to iOS tab-based application; where when you add more TabItem; it will have more option to go to other TabItem, instead of TabItem squeezed within the bottom

**Comment by imaNNeo** [comment]
Hi, sorry for the delay,
Okay, I will investigate and check it,
Thank you for the issue, and also pull requests are welcome ;)
If you have enough time and interest in it, try to fork and working on it.

**Comment by imaNNeo** [comment]
Hi, I investigated and I realized that it is not common to have a scrollable BottomBar.
Then if you are not convinced, let me know.
For now, I will close this Issue.
Thanks
