### ISSUE TITLE
Textsize of Menu titile

### ISSUE THREAD

**Issue by engdinesh** [imaNNeoFighT/circular_bottom_navigation#6]
How can we change the size of menu text.

**Comment by imaNNeo** [comment]
Hi,
Unfortunately, Github started banning Iranian users while ago,
If they didn't stop their action, I can't continue on this repo,
read more it [here](https://medium.com/@hamed/github-blocked-my-account-and-they-think-im-developing-nuclear-weapons-e7e1fe62cb74),
If you want to prevent this unfair action, give a start on this [repository](https://github.com/1995parham/github-do-not-ban-us) and say your support by creating an issue, and spread it.
Best regards,
Iman Khoshabi

**Comment by mderis** [comment]
@engdinesh dude your requested feature is added in PR #12 and you can use it soon. :-)
